### ISSUE TITLE
Library versioning

### ISSUE THREAD

**Issue by danilos1** [arangodb/go-driver#329] opened 2021-09-06 14:05 UTC
Good afternoon! It would be nice and conveniently, if library versions will be matched with the release ones. I.e. if we have the release version 1.2.0, then just ```go get github.com/arangodb/go-driver@v1.2.0```

**Comment by gunturaf** [comment] 2021-09-13 07:50
yes this causing issue in a go.mod environment,
also to pin version into git commit SHA is not that elegant in an ecosystem where tools like Dependabot or RenovateBot are involved because every time a new commit is added into the `master` branch, the bot will fetch those new commits, the problem is we (the users?) can't safely assume everything in the `master` branch is the stable version of the library.

I hope the arangodb team will consider this as a necessary addition (because it seems version tagging is can only be done by members of this library?)

Thanks!

**Comment by ajanikow** [comment] 2021-09-14 10:12
Hello! Starting from next minor release we will use Go compatible versioning (v1.x.x).

Best Regards,
Adam.

**Comment by nikita-vanyasin** [comment] 2022-03-18 14:25
Closing: go-driver now uses correct versioning.

**Closed by nikita-vanyasin** 2022-03-18 14:25 UTC
